$(document).ready(function(){
  $("#high").click(function(){
    $("li.high").fadeToggle('slow');
  });
  $("#mid").click(function(){
	$("li.mid").fadeToggle('slow');
  });
  $("#low").click(function(){
	$("li.low").fadeToggle('slow');
  });
});